version: '3.3'
services:
  pingbmwebapp:
    image: ${image_url}:latest
    environment:
      - AplloEnv=Dev
      - AplloMetaServer=http://192.168.1.115:9080
      - AplloAppId=positioning-web
    volumes:
      - /logs/testc:/app/App_Data
    ports:
      - "5001:80"
    container_name: "testc"
    restart: always
